apply plugin: 'com.android.library'

apply from: rootProject.file('gradle/android.gradle')

android {
  namespace 'io.freshpaint.android.wear'
}

dependencies {
  api project(':analytics')

  api 'com.google.android.gms:play-services-wearable:20.0.1'
}

apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
