version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  test:
    machine:
      image: android:2024.11.1
    resource_class: large
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Run Tests
          command: JAVA_OPTS="--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED" ./gradlew test
      - android/save-gradle-cache
      - android/save-build-cache
      - store_test_results:
          path: analytics/build/test-results
      - store_artifacts:
          path: analytics/build/reports/tests

  build:
    machine:
      image: android:2024.11.1
    resource_class: large
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Build Release AAR
          command: JAVA_OPTS="--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED" ./gradlew assembleRelease
      - run:
          name: Build Javadocs
          command: JAVA_OPTS="--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED" ./gradlew androidJavadocs
      - android/save-gradle-cache
      - android/save-build-cache
      - store_artifacts:
          path: analytics/build/outputs/aar
          destination: aar-files
      - store_artifacts:
          path: analytics/build/docs
          destination: javadocs
      - persist_to_workspace:
          root: .
          paths:
            - analytics/build/outputs/aar/*
            - analytics/build/docs/*

  publish-release:
    machine:
      image: android:2024.11.1
    resource_class: large
    steps:
      - checkout
      - attach_workspace:
          at: .
      - android/restore-gradle-cache
      - run:
          name: Publish Release to Sonatype Central
          command: echo "Replace me with an actual publish!"
      - android/save-gradle-cache

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test
      - build:
          requires:
            - test

      # Publish releases on master branch and tags
      - publish-release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
          context:
            - sonatype-central